; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = dfu
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SPIFlash @ ^4.3.4
  adafruit/Adafruit BusIO @ ^1.16.1
  adafruit/Adafruit MCP4725 @ ^2.0.2